name: Create Lane

on:
  pull_request:
    types: [opened]
    branches:
      - main
  push:
    branches-ignore:    
      - main

jobs:

  create_or_update_lane_and_export:
    name: create and export lane

    runs-on: ubuntu-latest

    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
      LANE_NAME: ${{ github.head_ref || github.ref_name }}

    container:
      image: docker://bitcli/bit:latest-node-16.15.0
    steps:
      - uses: teambit/setup-action@v2.02
        with:
          name: angular-github-actions
          BIT_TOKEN: ${{ env.BIT_TOKEN }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install and compile components
        run: bit install
      
      - name: Create Local Lane
        run: bit lane create $LANE_NAME

      - name: Switch to existing lane
        if: ${{ failure() }}
        run: bit lane switch $LANE_NAME

      - name: Snap All Components without building them
        run: |
          bit checkout head
          bit snap --message "TODO - grab git-message"
      - name: Export the Lane and the Components
        run: |
          bit export > .git/export_output.txt
          cat .git/export_output.txt
  
      - name: Commit .bitmap changes to PR
        uses: EndBug/add-and-commit@v9
        with:
          push: true
          message: 'update .bitmap'