name: Create Lane

on:
  pull_request:
    types: [opened]
    branches:
      - main
  push:
    branches-ignore:    
      - main

jobs:

  setup_npm:
    name: setup npm

    runs-on: ubuntu-latest

    # if: startsWith(github.event.pull_request.head.ref, 'components/')

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

  extract_local_lane_name:
    name: extract local lane name

    runs-on: ubuntu-latest

    outputs:
      extracted: ${{ steps.extract.outputs.replaced }}

    steps:
      - name: Replace illegal characters from head branch name
        id: extract
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: "/"
          string: ${{ github.event.pull_request.head.ref }}
          replace-with: "-"
          flags: "g"

  create_or_update_lane_and_export:
    name: create and export lane

    runs-on: ubuntu-latest

    needs: [setup_npm, extract_local_lane_name]

    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
      LANE_NAME: ${{ needs.extract_local_lane_name.outputs.extracted }}
      LANE_ARTIFACT_FILE_NAME: .git/${{ needs.extract_local_lane_name.outputs.extracted }}_scope.txt

    container:
      image: docker://bitcli/bit:latest
    steps:
      - uses: teambit/setup-action@v2.02
        with:
          name: angular-github-actions
          BIT_TOKEN: ${{ env.BIT_TOKEN }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install and compile components
        run: bit install
      
      - name: Create Local Lane
        run: bit lane create $LANE_NAME

      - name: Switch to existing lane
        if: ${{ failure() }}
        run: bit lane switch $LANE_NAME

      - name: Snap All Components without building them
        run: |
          bit checkout head
          bit snap --message "TODO - grab git-message"
      - name: Export the Lane and the Components
        run: |
          bit export > .git/export_output.txt
          cat .git/export_output.txt
  
      - name: Commit .bitmap changes to PR
        uses: EndBug/add-and-commit@v9
        with:
          push: true
          message: 'update .bitmap'