name: Merge Lane

on:
  pull_request:
    types: [closed]
    branches:    
      - main

jobs:


  merge_and_export_lane:
    name: merge and export lane

    runs-on: ubuntu-latest

    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
      LANE_NAME: ${{ github.head_ref || github.ref_name }}

    container:
      image: docker://bitcli/bit:latest-node-16.15.0
    steps:
      - uses: teambit/setup-action@v2.02
        with:
          name: Set up Bit
          BIT_TOKEN: ${{ env.BIT_TOKEN }}

      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Import from Remote Lane
        run: bit import

      - name: Switch to Main Lane and checkout latest
        run: bit lane switch main
      - name: Merge Lane to Main
        run: bit lane merge $SCOPE_NAME/$LANE_NAME
      - name: Tag all Components
        run: bit tag --patch
      - name: Export the Lane and the Components
        run: bit export
      - name: delete .bitmap
        run: TODO - need to find a way to paste the state of an empty .bitmap here.
      - name: empty .bitmap from pr
        uses: EndBug/add-and-commit@v9
        with:
          push: true
          message: 'remove .bitmap after merging'